# Generated by Django 4.1 on 2023-12-28 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=194, verbose_name='Full name')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='House number')),
                ('vehicle_sign', models.CharField(blank=True, max_length=7, null=True, verbose_name='Vehicle Sign')),
                ('entrance_time', models.DateTimeField(auto_now_add=True, verbose_name='Time of arrival')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Exiting time')),
                ('authorization_time', models.DateTimeField(blank=True, null=True, verbose_name='Entrance authorization time')),
                ('responsible', models.CharField(blank=True, max_length=194, verbose_name='Name of people responsible for the visitor')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porteiros.porteiro', verbose_name='Porteiro responsible for registering visit')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'db_table': 'visitor',
            },
        ),
    ]
